language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install .
  - pip install codecov
  - export PYTHONPATH="."  # No data is collected by `coverage` without this.

branches:
  only:
  - master
  - develop

script:
  - COVERAGE_FILE=.coverage_al coverage run tests/test_active_learning.py
  - COVERAGE_FILE=.coverage_s coverage run tests/test_stacking.py
  - COVERAGE_FILE=.coverage_te coverage run tests/test_target_encoding.py
  - coverage combine .coverage_al .coverage_s .coverage_te

after_success:
  - codecov

notifications:
  email:
    recipients:
      - nikolay.lysenko.1992@gmail.com
    on_success: never
    on_failure: always
